name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # 1. Gerekli Sistem Kütüphanelerini Yükle (Linux Sunucuya)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip build-essential git python3 python3-dev ffmpeg \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev \
            zlib1g-dev libgstreamer1.0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
            libffi-dev libssl-dev autoconf libtool libltdl-dev openjdk-17-jdk zip unzip

      # 2. Buildozer'ı Çalıştır ve APK Yap
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master

      # 3. Oluşan APK'yı Bize Ver (Artifacts Olarak Yükle)
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: namaz-takip-apk
          path: bin/*.apk
